travis:
  secure:
    BINSTAR_TOKEN: 1dnh1uag5IkxcNWhNWOvpikKkCANqGSpqXkxFqj2UebVAS6Fr9wWlDDdj2/bccgCszDh0Fnd4xsWk4W6XzN2o6ZPXL1vql1JNcY7aQnC5N8yqfK4R2+oDpbQVMmFT09GjVbAnL554j97/yxudDhzKrvZmjyf35c7JlXOj8TuAA4FNEnMkDTXN3VtEliIysTD8c+9ZqLgVnb9NAQHGa6cO2sy4bAQG6E5oqkK7ZDBnaEY0iNnuCZoz8Z32vp4+7rEvT2DSpnUR2LSQg22LAjTVYm+eMAik82FyGeOvPWiMEWslvr560nJKfZldYsj9atLUaZyqujwAGLfMm0xMt29vYrylTZ83YZ11yybPfuKe4AUvVA3iuy/zAhEqVlGENJkDsIwM7/Q6Q2tmSM9q3bXJfAlbucrGWsOBPT8IpNoK5965Ixr02KO7Cb4+lxXRxMx4cV2gSbHZiEpS4pKsAMZKn8fAaP0rcTFWNOr/Zk7+tMUQevSMdn3TPDdVdGZQQ7a/XlUfnjvInfGR9qJwgq+GFRKTqFnv9wDQo/37jQXQyfQujAaV7Do2nTcgWIbscCHRKdDY7h1zfmq6no1aBl80jotWejfoCR15BJGnDyTh/E3PodWlXVYVC3QPPp663lff6adrLbewVzyA/ZyLC09Cuj1/nC3lJ6qyxH5VIAPlxk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
