travis:
  secure:
    BINSTAR_TOKEN: vz7ErYwQy16PpG0vArsF+t78snRDo8TjlVIEtu9WU+RO+jdd/1dvY7E7XTQso4R5CsykLBrI60bd/fF0Ibas9gW8Ew55Vvcu7TEwpPLtI15c86lHKFNw9RJDMPV/wsgYb0hUUFBjYx0Mv+kPnskq7x0BsImp1CDXSbTha2mmFicmMjCpkEoYIoqF5iwtx6IbGEHSG/CiAUU0UynPM9HaZ8IqGqDNWqOxkj1kUuebjGzOdrokjcbvtDrATu7IccYQAJE4RxLcjwYQxB64ksE30VRNAOpxO3ohT4bQMlnsWR8G1iO3E+4Dz2upjj/57jMRrKocPZaiAaamkqyA+pcxERG6WOcoWSJNk7XRlcRkvkYpScZbM4j5atUgjxHeAX5x4GyPVYIXHJRBSTc5WmZdH1+3m3QXSxecF26A/seCHNv4fRgxKFcU1lofZo9CRgpx2X9OhuktzwALIDyBJogKDhddDkyaZdf0APHcJYrx4mU7vvmbWlrDwB9FRYA4yMzIHNIJSsaMdAUHGiDLfODGKYfcSVKViP3iJcnbLkQgBTMGPVUFyVKV7ngqIxk6GpUWLIod11tZZ1XWEd/EEx2xSLFqveWpGw9cFb1lBQKDTfrCMDJjCOCljPPcs9jDQ+fMwIzIqN5mFNrDrTkQRlfDp5G2yzzQtnApfr+c4BCkcNM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
